# Generated by Django 2.2.4 on 2019-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for category', unique=True)),
                ('description', models.TextField()),
                ('meta_description', models.CharField(help_text='Content description', max_length=500, verbose_name='Meta Description')),
                ('meta_keywpords', models.CharField(help_text='Content Keywords', max_length=500, verbose_name='Meta Keywords')),
                ('brand_status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for category', unique=True)),
                ('description', models.TextField()),
                ('meta_description', models.CharField(help_text='Content description', max_length=500, verbose_name='Meta Description')),
                ('meta_keywpords', models.CharField(help_text='Content Keywords', max_length=500, verbose_name='Meta Keywords')),
                ('category_status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='Unique value', max_length=500, unique=True)),
                ('description', models.TextField()),
                ('meta_description', models.CharField(help_text='Content description', max_length=500, verbose_name='Meta Description')),
                ('meta_keywpords', models.CharField(help_text='Content Keywords', max_length=500, verbose_name='Meta Keywords')),
                ('sku', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('image_url', models.CharField(max_length=250)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('product_status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive')])),
                ('brands', models.ManyToManyField(to='catalogueapp.Brand')),
                ('categories', models.ManyToManyField(to='catalogueapp.Category')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['created_date'],
            },
        ),
    ]
